version:  '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: desafio_app
    volumes:
      - .:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /var/www
    networks:
      - lumen

  web:
    image: nginx:alpine
    container_name: desafio_web
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - lumen

  mysql:
    image: mysql:5.7
    container_name: desafio_db
    environment:
      - MYSQL_DATABASE=desafio
      - MYSQL_DATABASE=password
    ports:
      - "3306:3306"
    networks:
      - lumen

networks:
  lumen:
    driver: bridge

